import { teamMembers } from 'src/DummyData/Usersdata.js';
import { initiativeComments } from 'src/DummyData/InitiativeCommentsdata.js';

export const initiatives = [
  {
    id: 1,
    objectiveId: 1,
    title: 'Fix Mobile Responsiveness',
    dueDate: '09-15-2025',
    progress: 25,
    isFavorite: true,
    commentIds: [1, 2],
    owner: teamMembers[0],
  },
  {
    id: 2,
    objectiveId: 1,
    title: 'Update OKR Dashboard',
    dueDate: '10-01-2025',
    progress: 60,
    isFavorite: true,
    commentIds: [3],
    owner: teamMembers[0],
  },
  {
    id: 3,
    objectiveId: 2,
    title: 'Launch Internal Newsletter',
    dueDate: '08-20-2026',
    progress: 80,
    isFavorite: false,
    commentIds: [],
    owner: teamMembers[2],
  },
  {
    id: 4,
    objectiveId: 2,
    title: 'Improve Onboarding Flow',
    dueDate: '09-30-2025',
    progress: 45,
    isFavorite: true,
    commentIds: [4],
    owner: teamMembers[3],
  },
  {
    id: 5,
    objectiveId: 3,
    title: 'Upgrade Security Protocols',
    dueDate: '05-15-2025',
    progress: 100,
    isFavorite: false,
    commentIds: [],
    owner: teamMembers[4],
  },
  {
    id: 6,
    objectiveId: 3,
    title: 'Automate Quarterly Reporting',
    dueDate: '06-01-2025',
    progress: 100,
    isFavorite: true,
    commentIds: [5],
    owner: teamMembers[5],
  },
];
