export const notificationsData = [
  {
    id: 1,
    message: 'Your report has been approved.',
    liked: true,
    read: false,
    comments: ['Great work!', 'Thanks for the update.'],
    tempComment: '',
  },
  {
    id: 2,
    message: 'Reminder: Submit your Q3 OKRs by Friday.',
    liked: false,
    read: false,
    comments: [],
    tempComment: '',
  },
  {
    id: 3,
    message: 'Your team has been assigned a new project.',
    liked: false,
    read: false,
    comments: ['Exciting!', 'Looking forward to it.'],
    tempComment: '',
  },
  {
    id: 4,
    message: 'System maintenance scheduled for Saturday.',
    liked: false,
    read: true,
    comments: [],
    tempComment: '',
  },
  {
    id: 5,
    message: 'Performance reviews are now open.',
    liked: true,
    read: true,
    comments: ['Noted!', 'Thanks.'],
    tempComment: '',
  },
  {
    id: 6,
    message: 'You have been mentioned in a company-wide post.',
    liked: false,
    read: true,
    comments: [],
    tempComment: '',
  },
]
